Switch to dotnet8 for compilation and target framewok
ZEISS/czicompress pull request #28
Opened 2023-11-15 11:43 UTC by m-ringler

## Description

Switch to .NET 8 and C#12.

Fixes #27 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

* PR build with unit tests
* manual test

## Checklist:

- [x] I followed the Contributing Guidelines.
- [x] I did a self-review.
- [x] I commented my code, particularly in hard-to-understand areas.
- [x] I updated the version of czishrink (MINOR), new version is 1.1.0
- [x] New and existing unit tests pass locally with my changes.

2023-11-15 23:40 UTC, FelixS90 requested changes

2023-11-15 23:40 UTC, FelixS90 commented on .github/workflows/czishrink_dotnet.yml
Can you as part of this PR remove the condition to be on `github.event_name == 'push'` in lines 120 and 134 (basically the last two steps in that job)?

I guess that the latest failure on _main_ might get fixed by this PR - not sure though, but it would be nice to have this covered on PR-level as well. Builds will anyway get deleted after a retention period - so that disk space will get freed soon-ish.

2023-11-16 10:53 UTC, m-ringler commented on .github/workflows/czishrink_dotnet.yml
Done and fixed the issue. Thanks for alerting me.

2023-11-16 11:02 UTC, FelixS90 approved these changes

2023-11-16 11:31 UTC, merged